name: patch
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  patch:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Packages
        uses: ConorMacBride/install-package@v1.1.0
        with:
          apt: patchutils
      - uses: actions/checkout@v4.0.0

      - name: Make patches
        if: steps.cache-patches.outputs.cache-hit != 'true'
        run: |
          chmod 755 .github/patch
          bash .github/patch

      - name: Cache patches
        id: cache-patches
        uses: actions/cache@v3.3.2
        with:
          path: patches
          key: ${{ runner.os }}-patches

      - name: Commit patches
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: "Update NW.js patches"
